# Generated by Django 4.1.5 on 2023-05-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkDiscover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='neighbors',
            field=models.ManyToManyField(blank=True, to='NetworkDiscover.device'),
        ),
    ]
