# Generated by Django 4.1.5 on 2023-05-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkDiscover', '0003_device_neighbors2_device_neighbors3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='neighbors',
        ),
        migrations.RemoveField(
            model_name='device',
            name='neighbors2',
        ),
        migrations.RemoveField(
            model_name='device',
            name='neighbors3',
        ),
        migrations.RemoveField(
            model_name='device',
            name='neighbors4',
        ),
        migrations.AlterField(
            model_name='device',
            name='device_ip',
            field=models.CharField(max_length=16),
        ),
    ]
