# Generated by Django 4.1.5 on 2023-05-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkDiscover', '0004_remove_device_neighbors_remove_device_neighbors2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbor',
            fields=[
                ('neighbor_id', models.AutoField(primary_key=True, serialize=False)),
                ('neighbor_name', models.CharField(max_length=100)),
                ('neighbor_ip', models.CharField(max_length=16)),
                ('origin', models.CharField(max_length=16)),
            ],
        ),
    ]
