# Generated by Django 4.1.5 on 2023-05-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkDiscover', '0005_neighbor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbor',
            name='origin',
            field=models.CharField(max_length=100),
        ),
    ]
